### ISSUE TITLE
This dependency was not found:

### ISSUE THREAD

**Issue by LiZeC123** [hiroppy/fusuma#170]
## Info

- Operating System:  Win 10
- Node Version: v10.15.1
- Browser Name and Version:  Chrome 75.0.3770.142

## Type

- [x] bug
- [ ] feature request

## For Bugs

I downloaded this project using npm yesterday. And I tried to start the sample code with npx, but got the following error message.

``` 
 ERROR  Failed to compile with 2 errors                                                                                                                         00:12:51

These dependencies were not found:

* \src\entryPoints\Client.js in multi webpack-hot-middleware/client?reload=true regenerator-runtime /src/entryPoints/Client.js ./index.js src/utils/customCss.js
* src\utils\customCss.js in multi webpack-hot-middleware/client?reload=true regenerator-runtime /src/entryPoints/Client.js ./index.js src/utils/customCss.js

To install them, you can run: npm install --save \src\entryPoints\Client.js src\utils\customCss.js
```

This seems to be missing some dependencies, but I have never used nodejs before, so I can't determine the specific reason. And in the installation process, there are still the following warnings

```
npm WARN dagre-d3-renderer@0.5.8 requires a peer of d3@^4.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN myslides@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

Because I don't know nodejs, I'm not sure if the above warning is the reason why the project can't run. Below is the full output during installation and operation

```
PS C:\Users\lizec\Documents\Blog\Fusuma> node -v
v10.15.1
PS C:\Users\lizec\Documents\Blog\Fusuma> npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (fusuma) myslides
version: (1.0.0)
description: None
entry point: (index.js)
test command:
git repository:
keywords:
author: LiZeC
license: (ISC) MIT
About to write to C:\Users\lizec\Documents\Blog\Fusuma\package.json:

{
  "name": "myslides",
  "version": "1.0.0",
  "description": "None",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "LiZeC",
  "license": "MIT"
}


Is this OK? (yes) yes
PS C:\Users\lizec\Documents\Blog\Fusuma> cat .\package.json
{
  "name": "myslides",
  "version": "1.0.0",
  "description": "None",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "LiZeC",
  "license": "MIT"
}
PS C:\Users\lizec\Documents\Blog\Fusuma>  npm i fusuma -D # yarn fusuma --dev
npm WARN deprecated intl-relativeformat@6.4.3: true

> core-js-pure@3.1.4 postinstall C:\Users\lizec\Documents\Blog\Fusuma\node_modules\core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> pose-core@2.1.0 postinstall C:\Users\lizec\Documents\Blog\Fusuma\node_modules\pose-core
> node ./scripts/postinstall.js || exit 0


      +-------------------------------------------------+
      |                                                 |
      |          Hey! Using Pose commercially?          |
      |                                                 |
      |         Pose is completely open source.         |
      |       Its continued development relies on       |
      |          contributions and sponsorship.         |
      |                                                 |
      |          Join us: patreon.com/popmotion         |
      |                                                 |
      +-------------------------------------------------+


> spawn-sync@1.0.15 postinstall C:\Users\lizec\Documents\Blog\Fusuma\node_modules\spawn-sync
> node postinstall


> caporal@1.2.0 postinstall C:\Users\lizec\Documents\Blog\Fusuma\node_modules\caporal
> (test -f ./node_modules/husky/bin/install.js && node ./node_modules/husky/bin/install.js) || exit 0


> cwebp-bin@5.1.0 postinstall C:\Users\lizec\Documents\Blog\Fusuma\node_modules\cwebp-bin
> node lib/install.js

  √ cwebp pre-build test passed successfully
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN dagre-d3-renderer@0.5.8 requires a peer of d3@^4.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN myslides@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ fusuma@1.14.0
added 1609 packages from 1024 contributors and audited 41051 packages in 142.182s
found 32 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\lizec\Documents\Blog\Fusuma>

PS C:\Users\lizec\Documents\Blog\Fusuma> ls


    目录: C:\Users\lizec\Documents\Blog\Fusuma


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2019/7/28      0:07                node_modules
d-----        2019/7/28      0:09                samples
-a----        2019/7/28      0:08           3921 output.txt
-a----        2019/7/28      0:07         546050 package-lock.json
-a----        2019/7/28      0:07            265 package.json
-a----        2019/7/28      0:03            460 新建文本文档.txt


PS C:\Users\lizec\Documents\Blog\Fusuma> cd .\samples\
PS C:\Users\lizec\Documents\Blog\Fusuma\samples> ls


    目录: C:\Users\lizec\Documents\Blog\Fusuma\samples


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2019/7/28      0:09                advanced
d-----        2019/7/28      0:09                intro
d-----        2019/7/28      0:09                issues


PS C:\Users\lizec\Documents\Blog\Fusuma\samples> cd .\intro\
PS C:\Users\lizec\Documents\Blog\Fusuma\samples\intro> ls


    目录: C:\Users\lizec\Documents\Blog\Fusuma\samples\intro


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2019/7/28      0:09                scripts
d-----        2019/7/28      0:09                slides
-a----        2019/7/27     16:46             74 .env.sample
-a----        2019/7/27     16:46            357 .fusumarc.yml
-a----        2019/7/27     16:46             23 index.js
-a----        2019/7/27     16:46           8784 package-lock.json
-a----        2019/7/27     16:46            665 package.json
-a----        2019/7/27     16:46          62328 StratumNo1 Medium.ttf
-a----        2019/7/27     16:46           1137 style.css


PS C:\Users\lizec\Documents\Blog\Fusuma\samples\intro> npx fusuma start
  √ cwebp pre-build test passed successfully
- Starting server...Error: no gitconfig to be found at C:\Users\lizec\Documents\Blog\Fusuma\samples\intro
    at C:\Users\lizec\AppData\Roaming\npm-cache\_npx\1176\node_modules\fusuma\node_modules\gitconfiglocal\index.js:13:27
    at C:\Users\lizec\AppData\Roaming\npm-cache\_npx\1176\node_modules\fusuma\node_modules\gitconfiglocal\index.js:48:48
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)
/ Starting server...

 ERROR  Failed to compile with 2 errors                                                                                                                         00:12:49

These dependencies were not found:

* \src\entryPoints\Client.js in multi webpack-hot-middleware/client?reload=true regenerator-runtime /src/entryPoints/Client.js ./index.js src/utils/customCss.js
* src\utils\customCss.js in multi webpack-hot-middleware/client?reload=true regenerator-runtime /src/entryPoints/Client.js ./index.js src/utils/customCss.js

To install them, you can run: npm install --save \src\entryPoints\Client.js src\utils\customCss.js
Listening on http://localhost:8080


 WAIT  Compiling...                                                                                                                                             00:12:50



 ERROR  Failed to compile with 2 errors                                                                                                                         00:12:51

These dependencies were not found:

* \src\entryPoints\Client.js in multi webpack-hot-middleware/client?reload=true regenerator-runtime /src/entryPoints/Client.js ./index.js src/utils/customCss.js
* src\utils\customCss.js in multi webpack-hot-middleware/client?reload=true regenerator-runtime /src/entryPoints/Client.js ./index.js src/utils/customCss.js

To install them, you can run: npm install --save \src\entryPoints\Client.js src\utils\customCss.js
终止批处理操作吗(Y/N)? y
PS C:\Users\lizec\Documents\Blog\Fusuma\samples\intro>
```

**Comment by hiroppy** [comment]
I cannot reproduce this issue on my PC(MacOS). Can you submit the reproducible repo?

**Comment by LiZeC123** [comment]
Today I tried to install this project on Ubuntu. This problem does not appear. So this should be a bug related to the Windows platform. Since I don't know nodejs, I can't analyze the cause of the error further.

If I find the reason for the error (I am learning nodejs), I will come back to discuss it with you.

**Comment by hiroppy** [comment]
Thank you for your investigation. I think this point is not good. https://github.com/hiroppy/fusuma/blob/master/packages/webpack/src/webpack.config.js#L19-L22

Could you modify from `/` to `\` this file in node_modules?

**Comment by LiZeC123** [comment]
After the above modification, this error did not appear. Now this project can run normally.  Thanks for your help!

**Comment by hiroppy** [comment]
ok, thank you for investigating. I'll change to it.
