### ISSUE TITLE
`fusuma build -d name` will cause error `Cannot find module 'undefined'`

### ISSUE THREAD

**Issue by chengluyu** [hiroppy/fusuma#281]
## Info

- Operating System: macOS
- Node Version: v14.9.0
- Browser Name and Version: Firefox Developer Edition 81.0b4 (64-bit)

## Type

- [x] bug
- [ ] feature request

## For Bugs

No reproducible repo but it’s **very easy** to reproduce.

### Expected Behavior

Built files are written in folder “public”.

### Actual Behavior

An error occurred.

```
$ /Users/[REDACTED]/test/node_modules/.bin/fusuma build -d public
⠼ Rendering components to HTML...Error: Cannot find module 'undefined'
    at webpackMissingModule (/Users/[REDACTED]/test/public/dist/entry.js:298:181)
    at Server (/Users/[REDACTED]/test/public/dist/entry.js:298:265)
    at processChild (/Users/[REDACTED]/test/public/dist/entry.js:1258:2450)
    at resolve (/Users/[REDACTED]/test/public/dist/entry.js:1257:122)
    at ReactDOMServerRenderer.render (/Users/[REDACTED]/test/public/dist/entry.js:1294:1153)
    at ReactDOMServerRenderer.read (/Users/[REDACTED]/test/public/dist/entry.js:1294:55)
    at renderToString (/Users/[REDACTED]/test/public/dist/entry.js:1333:116)
    at render (/Users/[REDACTED]/test/public/dist/entry.js:301:100)
    at /Users/[REDACTED]/test/node_modules/@fusuma/webpack/src/build.js:37:22
    at finalCallback (/Users/[REDACTED]/test/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/[REDACTED]/test/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/[REDACTED]/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/[REDACTED]/test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/[REDACTED]/test/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/[REDACTED]/test/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/[REDACTED]/test/node_modules/webpack/lib/Compiler.js:298:10 {
  code: 'MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

### How can we reproduce the behavior?

1. `yarn add --dev fusuma`
2. `yarn fusuma init`
3. `yarn fusuma build -d public`

**Comment by chengluyu** [comment]
I inspect some code and found another problem: if `-d public` is provided, the build destination will be “public/dist”. I’m not sure whether this is related to this issue. But I think this is unexpected. Generally, when users specify `-d folder`, they want files to be written directly to “folder”, not “folder/dist”.

Here are lines that my conclusion is based on.
https://github.com/hiroppy/fusuma/blob/d01bb1c3c303718145bfe3e0bead64917903624b/packages/fusuma/src/tasks.js#L144
https://github.com/hiroppy/fusuma/blob/d01bb1c3c303718145bfe3e0bead64917903624b/packages/webpack/src/webpack.config.js#L48

**Comment by hiroppy** [comment]
Thank you for reporting. I'll confirm it.

**Comment by hiroppy** [comment]
Sorry for the late reply, I've fixed this issue so closed, thanks!
