### ISSUE TITLE
Installation instructions are not accurate

### ISSUE THREAD

**Issue by mattouille** [hiroppy/fusuma#83]
I don't really know much about JS tooling or workflow, but I liked your tool and wanted to use it!

Unfortunately, the instructions you provided do not work.

```shell
$ npx fusuma start
⠸ Starting with webpack-dev-server...

 ERROR  Failed to compile with 5 errors                                                                                            1:00:25 PM

 error  in /usr/local/lib/node_modules/fusuma/src/client/src/index.js

Module build failed (from /usr/local/lib/node_modules/fusuma/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-syntax-dynamic-import' from '/Users/mouille/Projects/sre-basics'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/fusuma/node_modules/resolve/lib/sync.js:69:15)
    at resolveStandardizedName (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/partial.js:85:55)

 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server @babel/polyfill /usr/local/lib/node_modules/fusuma/src/client/src/index.js

 error  in (webpack)/hot/dev-server.js

Module build failed (from /usr/local/lib/node_modules/fusuma/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-syntax-dynamic-import' from '/Users/mouille/Projects/sre-basics'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/fusuma/node_modules/resolve/lib/sync.js:69:15)
    at resolveStandardizedName (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/partial.js:85:55)

 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server @babel/polyfill /usr/local/lib/node_modules/fusuma/src/client/src/index.js

 error  in (webpack)-dev-server/client?http://localhost:8080

Module build failed (from /usr/local/lib/node_modules/fusuma/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-syntax-dynamic-import' from '/Users/mouille/Projects/sre-basics'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/fusuma/node_modules/resolve/lib/sync.js:69:15)
    at resolveStandardizedName (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/partial.js:85:55)

 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server @babel/polyfill /usr/local/lib/node_modules/fusuma/src/client/src/index.js

 error  in /usr/local/lib/node_modules/fusuma/node_modules/@babel/polyfill/lib/index.js

Module build failed (from /usr/local/lib/node_modules/fusuma/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-syntax-dynamic-import' from '/Users/mouille/Projects/sre-basics'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/fusuma/node_modules/resolve/lib/sync.js:69:15)
    at resolveStandardizedName (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/usr/local/lib/node_modules/fusuma/node_modules/@babel/core/lib/config/partial.js:85:55)

 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server @babel/polyfill /usr/local/lib/node_modules/fusuma/src/client/src/index.js

 error


Running at http://localhost:8080
```

**Comment by mattouille** [comment]
I finally got everything working after cycling through error messages. There's probably a simpler way to install all these deps but I'm clueless as to how.

**Comment by hiroppy** [comment]
fmmm... fusuma has already had `@babel/plugin-syntax-dynamic-import`. 🤔 

https://github.com/hiroppy/fusuma/blob/master/package.json#L38

**Comment by mattouille** [comment]
As I said, I don't really know anything about Javascript tooling. I did `npm i fusuma -g` and when I tried to `npx fusuma start` that's the message I got.

**Comment by hiroppy** [comment]
I've upgraded directory structure. I hope this has been fixed. If it has not been fixed, please feel free to reopen it.
